### PR TITLE
Search filter

### LINKED ISSUE #16: Chrometana should not redirect Bing searches from the Settings app
Hi there,

An example of what the subject mentions, would be going to Settings -> Update & Security -> Windows Update tab -> Click the link "Learn More" under "Looking for more info on latest updates".

This takes you to a Bing search, where you get a card with info from Microsoft about this. However, with Chrometana, it takes you to a Google search where no such information is presented. This shouldn't happen.

### PR DESCRIPTION
**Pull request by kyleladd**
Redirect all Bing searches or only searches that originate from Cortana. Might need to explain what it redirects by default in the settings menu (Some sort of helper text). By default Chrometana redirects only searches that originate from Cortana....
resolve #16

### CODE REVIEW

**Comment by TheoBr** [comment]
Code looks good, trying on my test virt now

**Comment by kyleladd** [comment]
This could've/should've been pulled out into a function which would make unit testing it easier in the future: https://github.com/TheoBr/Chrometana/pull/17/files#diff-30376e8249ccb7e6d99b75f6dcb969e7R10

**Comment by ClairePitman** [comment]
I think All Bing search might be a little too general. For example I want the Bing searches for updates to go to bing but I want every other search to use google. I think A lot of people will check the box and not realize that they are disabling bing searches for updates which are very helpful.

**Comment by TheoBr** [comment]
@ClairePitman : I think trying to explain Windows 10's strange help request behavior would be too big a design challenge to use in that way.

I feel as though the toggles @kyleladd added are representative of the two use cases that we should cover:
1. Changing Cortana's search engine
2. Hiding Bing forever

A third use-case of hiding "all of Bing but WIndows 10 help dialogues" is hard to conceptualize, and even harder to explain (as I'm sure you noticed as you tried hahaha). 

For now, I think this works perfect, and I would love to ship it in the beta.

**Comment by kyleladd** [comment]
Bing searches for updates being what source (form=____)? the settings app? The sources that I've identified so far are listed https://github.com/TheoBr/Chrometana/issues/16 . 

Anyway, the logic is there as to how we can implement those additional toggles in the future. Right now, I'm not sure as to what instance you are trying to explain (sorry). A video or pictures would help greatly.
Thanks

**Comment by TheoBr** [comment]
@kyleladd : I think she's referring to queries made from the settings app as "Bing searches for updates", which is &form=S00028

**Comment by TheoBr** [comment]
I'm merging this

**Comment by kyleladd** [comment]
kk, intially have Chrometana only redirect Cortana searches; allow the user to opt into redirect all Bing searches; once they have opted to redirect all Bing searches, provide exclusions according to their source (such as the settings app:S00028): https://github.com/TheoBr/Chrometana/pull/18

**Pull request merged**
